# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171125_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
